spring:
  datasource:
    url: jdbc:mysql://localhost:33062/spiral?charcterEncoding=utf8&useUnicode=true&serverTimezone=UTC
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
