spring:
  datasource:
    url: jdbc:mysql://localhost:33062/spiral?charcterEncoding=utf8&useUnicode=true&serverTimezone=UTC
    username: root
    password: password
  liquibase:
    change-log: classpath:db/db.changelog-master.xml
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /api-docs
